apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-database
spec:
  provider:
    vault:
      server: https://vault.keybuzz.io:8200
      path: database
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-keybuzz
          serviceAccountRef:
            name: eso-keybuzz-sa
            namespace: keybuzz-system
      version: v1
