apiVersion: apps/v1
kind: Deployment
metadata:
  name: keybuzz-api
  namespace: keybuzz-api-dev
  labels:
    app: keybuzz-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keybuzz-api
  template:
    metadata:
      labels:
        app: keybuzz-api
    spec:
      containers:
      - name: keybuzz-api
        image: ghcr.io/keybuzzio/keybuzz-api:v0.1.26-dev
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: '3001'
        - name: NODE_ENV
          value: development
        - name: PGHOST
          value: 10.0.0.122
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: keybuzz-api-postgres
              key: PGPORT
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: keybuzz-api-postgres
              key: PGDATABASE
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: keybuzz-api-postgres
              key: PGUSER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: keybuzz-api-postgres
              key: PGPASSWORD
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 15
      imagePullSecrets:
      - name: ghcr-cred
