apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keybuzz-api-postgres
  namespace: keybuzz-api-dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend-database
  target:
    name: keybuzz-api-postgres
    creationPolicy: Owner
    template:
      type: Opaque
      mergePolicy: Merge
      data:
        PGHOST: |
          10.0.0.10
        PGPORT: |
          5432
        PGDATABASE: |
          keybuzz
  data:
    - secretKey: PGUSER
      remoteRef:
        key: database/creds/keybuzz-api-db
        property: username
    - secretKey: PGPASSWORD
      remoteRef:
        key: database/creds/keybuzz-api-db
        property: password
