apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keybuzz-api-jwt
  namespace: keybuzz-api-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keybuzz-api-jwt
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: keybuzz/dev/jwt
        property: JWT_SECRET
    - secretKey: COOKIE_SECRET
      remoteRef:
        key: keybuzz/dev/jwt
        property: COOKIE_SECRET
