apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keybuzz-api-dev
resources:
- clustersecretstore-vault-database.yaml
- externalsecret-postgres.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- outbound-worker-deployment.yaml
- outbound-tick-cronjob.yaml
