apiVersion: v1
kind: Service
metadata:
  name: keybuzz-api
  namespace: keybuzz-api-dev
  labels:
    app: keybuzz-api
spec:
  type: ClusterIP
  selector:
    app: keybuzz-api
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
