# PH-S01: Service seller-api
apiVersion: v1
kind: Service
metadata:
  name: seller-api
  namespace: keybuzz-seller-dev
  labels:
    app: seller-api
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    app: seller-api
