apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keybuzz-client
  namespace: keybuzz-client-dev
  annotations:
    
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - client-dev.keybuzz.io
      secretName: keybuzz-client-tls
  rules:
    - host: client-dev.keybuzz.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keybuzz-client
                port:
                  number: 3000
