---
# RabbitMQ HA Configuration Variables
# TODO PH6-Vault: d√©placer rabbitmq_password dans Vault et le lire via External Secrets

# RabbitMQ Authentication
rabbitmq_default_user: "keybuzz"
rabbitmq_password: "{{ vault_rabbitmq_password | default('ChangeMeInPH6-Vault') }}"

# Cluster Configuration
rabbitmq_cluster_first_node: "queue-01"
rabbitmq_cluster_nodes:
  - "queue-01"
  - "queue-02"
  - "queue-03"

# Network Configuration
rabbitmq_amqp_port: 5672
rabbitmq_management_port: 15672
rabbitmq_epmd_port: 4369
rabbitmq_cluster_port: 25672

# Data Directory
rabbitmq_data_dir: "/data/rabbitmq"

# Feature flags
rabbitmq_clean_start: false  # Set to true for clean cluster initialization

