apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alerting-smtp-dev
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: alerting-smtp-dev
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: keybuzz/observability/smtp/dev
        property: host
    - secretKey: port
      remoteRef:
        key: keybuzz/observability/smtp/dev
        property: port
    - secretKey: username
      remoteRef:
        key: keybuzz/observability/smtp/dev
        property: username
    - secretKey: password
      remoteRef:
        key: keybuzz/observability/smtp/dev
        property: password
    - secretKey: from
      remoteRef:
        key: keybuzz/observability/smtp/dev
        property: from
    - secretKey: to_default
      remoteRef:
        key: keybuzz/observability/smtp/dev
        property: to_default
    - secretKey: require_tls
      remoteRef:
        key: keybuzz/observability/smtp/dev
        property: require_tls