apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alerting-slack-dev
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: alerting-slack-dev
    creationPolicy: Owner
  data:
    - secretKey: webhook_url
      remoteRef:
        key: keybuzz/observability/slack/dev
        property: webhook_url
    - secretKey: channel
      remoteRef:
        key: keybuzz/observability/slack/dev
        property: channel