apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-admin-prod
  namespace: keybuzz-admin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - admin.keybuzz.io
    secretName: keybuzz-admin-prod-tls
  rules:
  - host: admin.keybuzz.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keybuzz-admin
            port:
              number: 3000

