apiVersion: v1
kind: Service
metadata:
  name: keybuzz-website
  namespace: keybuzz-website-dev
  labels:
    app: keybuzz-website
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: keybuzz-website
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http