apiVersion: v1
kind: Service
metadata:
  name: keybuzz-admin
  namespace: keybuzz-admin-dev
  labels:
    app: keybuzz-admin
    tier: frontend
    env: dev
spec:
  type: ClusterIP
  selector:
    app: keybuzz-admin
    tier: frontend
    env: dev
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP

