apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: keybuzz-ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: litellm-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  refreshInterval: 1h
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: secret/keybuzz/litellm/master_key
        property: value
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/keybuzz/litellm/database_url
        property: value
    - secretKey: LITELLM_DATABASE_URL
      remoteRef:
        key: secret/keybuzz/litellm/database_url
        property: value
    - secretKey: USE_PRISMA_MIGRATE
      remoteRef:
        key: secret/keybuzz/litellm/use_prisma_migrate
        property: value
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: secret/keybuzz/ai/openai_api_key
        property: value
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: secret/keybuzz/ai/anthropic_api_key
        property: value

