apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: keybuzz-ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: litellm-secret
    creationPolicy: Owner
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: secret/keybuzz/litellm/master_key
        property: value
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/keybuzz/litellm/database_url
        property: value
    - secretKey: LITELLM_DATABASE_URL
      remoteRef:
        key: secret/keybuzz/litellm/database_url
        property: value
    - secretKey: USE_PRISMA_MIGRATE
      remoteRef:
        key: secret/keybuzz/litellm/use_prisma_migrate
        property: value
