apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keybuzz-ai
resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml


# External Secrets
- external-secret.yaml
- cluster-secret-store.yaml
