apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: keybuzz-ai
type: Opaque
stringData:
  LITELLM_MASTER_KEY: "dd511f0682d05a1335324c5b4faf6beedee203eb915e7035850e9ca225777426"

