apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keybuzz-ses-secrets
  namespace: keybuzz-api-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keybuzz-ses
    creationPolicy: Owner
  data:
    - secretKey: AWS_SES_ACCESS_KEY_ID
      remoteRef:
        key: secret/keybuzz/ses
        property: access_key_id
    - secretKey: AWS_SES_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/keybuzz/ses
        property: secret_access_key
    - secretKey: AWS_SES_REGION
      remoteRef:
        key: secret/keybuzz/ses
        property: region
    - secretKey: AWS_SES_FROM_EMAIL
      remoteRef:
        key: secret/keybuzz/ses
        property: from_email
