apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keybuzz-auth-secrets
  namespace: keybuzz-client-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keybuzz-auth
    creationPolicy: Owner
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: secret/keybuzz/auth
        property: nextauth_secret
    - secretKey: NEXTAUTH_URL
      remoteRef:
        key: secret/keybuzz/auth
        property: nextauth_url
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: secret/keybuzz/auth
        property: google_client_id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: secret/keybuzz/auth
        property: google_client_secret
    - secretKey: AZURE_AD_CLIENT_ID
      remoteRef:
        key: secret/keybuzz/auth
        property: azure_ad_client_id
    - secretKey: AZURE_AD_CLIENT_SECRET
      remoteRef:
        key: secret/keybuzz/auth
        property: azure_ad_client_secret
    - secretKey: AZURE_AD_TENANT_ID
      remoteRef:
        key: secret/keybuzz/auth
        property: azure_ad_tenant_id
