apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"keybuzz-backend","namespace":"keybuzz-api"},"spec":{"ports":[{"name":"http","port":4000,"protocol":"TCP","targetPort":4000}],"type":"ClusterIP"}}
  creationTimestamp: "2025-12-16T20:36:47Z"
  name: keybuzz-backend
  namespace: keybuzz-api
  resourceVersion: "1879034"
  uid: 783be499-86c0-4d47-a4e6-2abcd251fdbc
spec:
  clusterIP: 10.101.235.28
  clusterIPs:
  - 10.101.235.28
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: 4000
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
