apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keybuzz-backend-db
  namespace: keybuzz-backend-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keybuzz-backend-db
    creationPolicy: Merge
  data:
    - secretKey: PGHOST
      remoteRef:
        key: keybuzz/dev/backend-postgres
        property: PGHOST
    - secretKey: PGPORT
      remoteRef:
        key: keybuzz/dev/backend-postgres
        property: PGPORT
    - secretKey: PGDATABASE
      remoteRef:
        key: keybuzz/dev/backend-postgres
        property: PGDATABASE
    - secretKey: PGUSER
      remoteRef:
        key: keybuzz/dev/backend-postgres
        property: PGUSER
    - secretKey: PGPASSWORD
      remoteRef:
        key: keybuzz/dev/backend-postgres
        property: PGPASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: keybuzz/dev/backend-postgres
        property: DATABASE_URL
