apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keybuzz-backend-dev

resources:
  - namespace.yaml
  - secret-db.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: keybuzz-backend
  app.kubernetes.io/instance: keybuzz-backend-dev
  app.kubernetes.io/part-of: keybuzz
  environment: dev
